/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        Button: (typeof import('./src/components/ui/button/Button.vue'))['default']
        ElButton: (typeof import('element-plus/es'))['ElButton']
        HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
        NavComponent: (typeof import('./src/components/NavComponent.vue'))['default']
    }
}
