---
    name: Build and Deploy Vue App to CloudFront
    on:
        push:
            branches: [ main ]
    jobs:
        build-and-deploy:
            name: Build and Deploy
            runs-on: ubuntu-latest
            env:
                BUCKET: quicktailorbucket
                DIST: build
                REGION: us-west-2
                DIST_ID: E3JJUGWID1KV7V

            steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: secrets.ACCESS_KEY_ID
                aws-secret-access-key: secrets.SECRET_ACCESS_KEY
                aws-region: us-west-2
            
            - name: Install Dependencies
              run: |
                node --version
                npm ci --production
            
            - name: Build Static Website
              run: npm run build

            - name: Copy files to the producirton website with the AWS CLI
              run: aws s3 sync build s3://quicktailorbucket

            - name: Copy files to the production website with the AWS CLI
              run: aws cloudfront create-invalidation --distribution-id E3JJUGWID1KV7V --paths "/*"
