---
    name: Build and Deploy Vue App to CloudFront
    on:
        push:
            branches: [ main ]
    jobs:
        build-and-deploy:
            name: Build and Deploy
            runs-on: ubuntu-latest
            permissions:
                id-token: write
                contents: read        
            env:
                BUCKET: quicktailorbucket
                DIST: ./frontend/dist
                DIST_ID: E3JJUGWID1KV7V
                ROLE_TO_ASSUME: arn:aws:iam::339712804477:role/ghactionsrole
            environment: aws-s3-deploy

            steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@master
              with:
                aws-region: us-west-2      
                role-to-assume: ${{ env.ROLE_TO_ASSUME }}
            
            - name: Install Dependencies
              run: |
                cd ./frontend
                node --version
                npm ci
            
            - name: Build Static Website
              run: |
                cd ./frontend
                npm run build

            - name: Copy files to the producirton website with the AWS CLI
              run: aws s3 sync ${{ env.DIST }} s3://${{ env.BUCKET }}

            - name: Copy files to the production website with the AWS CLI
              run: aws cloudfront create-invalidation --distribution-id ${{env.DIST_ID}} --paths "/*"
