---
    name: Check deployment works
    on:
        pull_request:
            types: [opened, reopened]
            branches: ['main']
    jobs:
        deploy-check:
            name: Deploy Check
            runs-on: ubuntu-latest
            permissions:
                id-token: write
                contents: read        
            env:
                BUCKET: quicktailorbucket
                DIST: ./frontend/dist
                DIST_ID: E3JJUGWID1KV7V
                ROLE_TO_ASSUME: arn:aws:iam::339712804477:role/ghactionsrole
            environment: aws-s3-deploy

            steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@master
              with:
                aws-region: us-west-2      
                role-to-assume: ${{ env.ROLE_TO_ASSUME }}
            
            - name: Install Dependencies
              run: |
                cd ./frontend
                node --version
                npm ci
            
            - name: Build Static Website
              run: |
                cd ./frontend
                npm run build
